결과로 저장되는 CSV 파일이 원본과 달리 역순으로 정렬되어있음을 주의. (만약 원본과 같은 순서로 정렬하고 싶다면 'date'를 기준으로 내림차순 정렬하면 됨)

In [71]:
import pandas as pd
df = pd.read_csv('/collectKODEX200.csv').drop('Unnamed: 0', axis=1) # 첫번째 열 제거
print(df.head())

             date   open   high    low  close  volume  trade_volume
0  20221209153000  31230  31230  31230  31230   55738    1740697740
1  20221209151900  31210  31225  31210  31220    1982      61878040
2  20221209151800  31210  31215  31200  31210    7003     218563630
3  20221209151700  31215  31225  31200  31205    5870     183173350
4  20221209151600  31240  31240  31215  31215    2961      92427615

In [72]:
df = df.sort_values('date').reset_index(drop=True) # 날짜 오름차순 정렬
print(df.head()) 
print(df.tail())

             date   open   high    low  close  volume  trade_volume
0  20211201090000  36742  36932  36742  36825   81467    3000022275
1  20211201090100  36830  36957  36830  36937   97355    3596001635
2  20211201090200  36927  36991  36927  36932   57278    2115391096
3  20211201090300  36942  37001  36942  36991   19861     734678251
4  20211201090400  36991  37011  36962  36972   13302     491801544
                 date   open   high    low  close  volume  trade_volume
96961  20221209151600  31240  31240  31215  31215    2961      92427615
96962  20221209151700  31215  31225  31200  31205    5870     183173350
96963  20221209151800  31210  31215  31200  31210    7003     218563630
96964  20221209151900  31210  31225  31210  31220    1982      61878040
96965  20221209153000  31230  31230  31230  31230   55738    1740697740

In [73]:
df['sub_tv']=0
for i in range(1, 96966):
  df['sub_tv'][i] = df['trade_volume'][i]-df['trade_volume'][i-1]

In [64]:
print(df.head())
print(df.tail())

             date   open   high    low  close  volume  trade_volume  \
0  20211201090000  36742  36932  36742  36825   81467    3000022275
1  20211201090100  36830  36957  36830  36937   97355    3596001635
2  20211201090200  36927  36991  36927  36932   57278    2115391096
3  20211201090300  36942  37001  36942  36991   19861     734678251
4  20211201090400  36991  37011  36962  36972   13302     491801544

       sub_tv
0           0
1   595979360
2 -1480610539
3 -1380712845
4  -242876707
                 date   open   high    low  close  volume  trade_volume  \
96961  20221209151600  31240  31240  31215  31215    2961      92427615
96962  20221209151700  31215  31225  31200  31205    5870     183173350
96963  20221209151800  31210  31215  31200  31210    7003     218563630
96964  20221209151900  31210  31225  31210  31220    1982      61878040
96965  20221209153000  31230  31230  31230  31230   55738    1740697740

           sub_tv
96961  -389982195
96962    90745735
96963    35390280
96964  -156685590
96965  1678819700

In [74]:
df['label'] = 'H'

In [75]:
ishold = False # 초기 상태 False
newdf = df.copy() # df 참조 오류때문에 copy함
for i in range(1, 96966):
  # 보유중이지 않고, 10억보다 크면
  if (ishold == False) and (newdf['sub_tv'][i]>1000000000):
    newdf['label'][i+1] = 'B' # 다음 분봉에 매수
    ishold = True # 보유 중으로 변경
  # 보유중이고, -10억보다 작으면
  elif (ishold == True) and (newdf['sub_tv'][i]<-1000000000):
    newdf['label'][i+1] = 'S' # 다음 분봉에 매도
    ishold = False
  # 보유하고 있지 않거나, -10억<sub_tv<10억인 경우
  else:
    pass # H(아무것도 하지 않음)

<ipython-input-75-8c391cbf0d7b>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['label'][i+1] = 'B' # 다음 분봉에 매수
<ipython-input-75-8c391cbf0d7b>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['label'][i+1] = 'S' # 다음 분봉에 매도

In [76]:
print(newdf[:50]) # 50번째까지 출력하여, B와 S가 순서대로 출력되는지 확인

              date   open   high    low  close  volume  trade_volume  \
0   20211201090000  36742  36932  36742  36825   81467    3000022275
1   20211201090100  36830  36957  36830  36937   97355    3596001635
2   20211201090200  36927  36991  36927  36932   57278    2115391096
3   20211201090300  36942  37001  36942  36991   19861     734678251
4   20211201090400  36991  37011  36962  36972   13302     491801544
5   20211201090500  36962  36962  36879  36879   20260     747168540
6   20211201090600  36874  36903  36805  36805   38408    1413606440
7   20211201090700  36800  36825  36771  36781   42830    1575330230
8   20211201090800  36776  36790  36742  36746   11226     412510596
9   20211201090900  36746  36869  36746  36849   51686    1904577414
10  20211201091000  36854  36918  36835  36918   19066     703878588
11  20211201091100  36918  36927  36883  36908    8039     296703412
12  20211201091200  36898  36942  36898  36903   21819     805186557
13  20211201091300  36898  36913  36844  36854   19864     732067856
14  20211201091400  36859  36903  36844  36844   24650     908204600
15  20211201091500  36839  36859  36766  36771   22227     817309017
16  20211201091600  36776  36781  36702  36712   29329    1076726248
17  20211201091700  36707  36727  36644  36644   57828    2119049232
18  20211201091800  36649  36746  36634  36746   28176    1035355296
19  20211201091900  36751  36751  36644  36722   33140    1216967080
20  20211201092000  36712  36800  36693  36795   45457    1672590315
21  20211201092100  36800  36844  36756  36781   51485    1893669785
22  20211201092200  36795  36800  36742  36795   26640     980218800
23  20211201092300  36800  36864  36800  36849   43361    1597809489
24  20211201092400  36859  36893  36859  36874    6180     227881320
25  20211201092500  36879  36893  36849  36874   23341     860676034
26  20211201092600  36869  36918  36820  36913   17395     642101635
27  20211201092700  36908  36947  36908  36918   44786    1653409548
28  20211201092800  36923  36942  36903  36908   17015     627989620
29  20211201092900  36903  36918  36849  36859   13580     500545220
30  20211201093000  36859  36942  36859  36932   14091     520408812
31  20211201093100  36932  36957  36918  36942   29879    1103790018
32  20211201093200  36947  36947  36913  36927    4894     180720738
33  20211201093300  36923  36932  36903  36932    5705     210697060
34  20211201093400  36932  36947  36918  36937    3434     126841658
35  20211201093500  36923  36923  36879  36903   17775     655950825
36  20211201093600  36903  36913  36854  36869    9879     364228851
37  20211201093700  36859  36864  36781  36795   25026     920831670
38  20211201093800  36800  36835  36786  36795   18031     663450645
39  20211201093900  36810  36927  36810  36927   19769     730009863
40  20211201094000  36923  36967  36923  36957   47476    1754570532
41  20211201094100  36957  36972  36927  36967    9610     355252870
42  20211201094200  36972  36986  36957  36962   22248     822330576
43  20211201094300  36967  36972  36937  36942    3239     119655138
44  20211201094400  36942  36986  36942  36957   34950    1291647150
45  20211201094500  36952  36986  36952  36981    7389     273252609
46  20211201094600  36986  37011  36986  37006   39902    1476613412
47  20211201094700  37011  37011  36967  36967    6613     244462771
48  20211201094800  36976  36981  36927  36937   10989     405900693
49  20211201094900  36942  36976  36923  36976    9667     357446992

        sub_tv label
0            0     H
1    595979360     H
2  -1480610539     H
3  -1380712845     H
4   -242876707     H
5    255366996     H
6    666437900     H
7    161723790     H
8  -1162819634     H
9   1492066818     H
10 -1200698826     B
11  -407175176     S
12   508483145     H
13   -73118701     H
14   176136744     H
15   -90895583     H
16   259417231     H
17  1042322984     H
18 -1083693936     B
19   181611784     S
20   455623235     H
21   221079470     H
22  -913450985     H
23   617590689     H
24 -1369928169     H
25   632794714     H
26  -218574399     H
27  1011307913     H
28 -1025419928     B
29  -127444400     S
30    19863592     H
31   583381206     H
32  -923069280     H
33    29976322     H
34   -83855402     H
35   529109167     H
36  -291721974     H
37   556602819     H
38  -257381025     H
39    66559218     H
40  1024560669     H
41 -1399317662     B
42   467077706     S
43  -702675438     H
44  1171992012     H
45 -1018394541     B
46  1203360803     S
47 -1232150641     B
48   161437922     S
49   -48453701     H

In [78]:
openprice = 0 # 초기값 0
result = [] # 수익 리스트
for i in range(96966):
  if newdf['label'][i] == 'B':
    openprice = newdf['open'][i] # B로 레이블되었을 때 현재가
  elif newdf['label'][i] == 'S':
    result.append(newdf['open'][i] - openprice)
  else:
    pass

In [84]:
print(sum(result)) # 해당 전략으로 매수/매도시 1주당 926585의 수익을 얻을 수 있음

926585

In [ ]:
newdf.to_csv('NewKODEX200.csv') # csv 파일 저장